# Generated by Django 6.1 on 2026-08-28 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('companies', '0003_alter_company_created_by_companysetting'),
        ('employees', '0002_remove_employee_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['asset_code']},
        ),
        migrations.AlterField(
            model_name='asset',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('REPAIR', 'In Repair'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=30),
        ),
    ]
