# Generated by Django 5.0.14 on 2026-08-31 06:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_alter_shift_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY_FIRST_HALF', 'Half Day - First Half'), ('HALF_DAY_SECOND_HALF', 'Half Day - Second Half'), ('PERMISSION', 'Permission'), ('LATE_ENTRY', 'Late Entry'), ('EARLY_EXIT', 'Early Exit'), ('WORK_FROM_HOME', 'Work From Home'), ('ON_DUTY', 'On Duty')], default='FULL_DAY', max_length=30),
        ),
        migrations.AddField(
            model_name='attendance',
            name='early_exit_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes left early compared to shift end. Auto-calculated.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes late compared to shift start after grace. Auto-calculated.'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='permission_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='permission_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='permission_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='break_duration',
            field=models.PositiveIntegerField(default=0, help_text='Scheduled break in minutes applied to net working hours. 0 means no break configured.'),
        ),
        migrations.AddField(
            model_name='shift',
            name='full_day_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Scheduled net full-day hours. Leave blank to auto-derive from start_time/end_time minus break.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='grace_time',
            field=models.PositiveIntegerField(default=0, help_text='Grace period in minutes before a late check-in is counted. 0 means no grace.'),
        ),
        migrations.AddField(
            model_name='shift',
            name='minimum_half_day_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.00'), help_text='Minimum worked hours required for a full day. Used for half-day timing.', max_digits=5),
        ),
    ]
