# Generated by Django 6.1 on 2026-09-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_branch'),
        ('payroll', '0003_employee_salary_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='calendar_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='conveyance_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='esi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='half_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='holidays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='hra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='lop_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Days without pay (unpaid leave + unauthorised absence).', max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='lop_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='OT rate per hour applied for this period. 0 means the derived fallback rate was used.', max_digits=9),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='pf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='special_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tds',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='unpaid_leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='week_offs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Legacy aggregate deduction (treated as an advance/other deduction in payroll).', max_digits=12),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='gross_salary',
            field=models.DecimalField(decimal_places=2, help_text='Total earnings excluding OT (basic + bonus + allowances).', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('payroll_run', 'employee'), name='unique_payslip_run_employee'),
        ),
    ]
