# Generated by Django 6.1 on 2026-09-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeesalary_conveyance_allowance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='pay_date',
            field=models.DateField(blank=True, help_text='Date on which salaries are paid.', null=True),
        ),
    ]
