# Generated by Django 6.1 on 2026-09-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_payrollrun_pay_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesalary',
            old_name='hra',
            new_name='dearness_allowance',
        ),
        migrations.AddField(
            model_name='payslip',
            name='dearness_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='no_of_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Present days used for pro-rata.', max_digits=6),
        ),
        migrations.AddField(
            model_name='payslip',
            name='per_day_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total monthly / working days.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_monthly',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Basic + DA, full month amount.', max_digits=12),
        ),
    ]
