# Generated by Django 6.1 on 2026-08-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('COMPANY_ADMIN', 'Company Admin'), ('HR_MANAGER', 'HR Manager'), ('HR_EXECUTIVE', 'HR Executive'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('REPORTING_MANAGER', 'Reporting Manager'), ('PAYROLL_MANAGER', 'Payroll Manager'), ('ACCOUNTS_MANAGER', 'Accounts Manager'), ('RECRUITER', 'Recruiter'), ('EMPLOYEE', 'Employee'), ('AUDITOR', 'Auditor')], db_index=True, default='EMPLOYEE', max_length=30),
        ),
    ]
