# Generated by Django 6.1 on 2026-09-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='exit_date',
            field=models.DateField(blank=True, help_text='Date the employee left. Auto-set when status changes to Inactive or Exited.', null=True),
        ),
    ]
