# Generated by Django 6.1 on 2026-08-28 19:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_created_by_companysetting'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-applied_on']},
        ),
        migrations.AlterModelOptions(
            name='jobopening',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='candidate',
            name='applied_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='interview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='stage',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('SCREENING', 'Screening'), ('INTERVIEW', 'Interview'), ('SELECTED', 'Selected'), ('OFFERED', 'Offered'), ('JOINED', 'Joined'), ('REJECTED', 'Rejected')], default='APPLIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_openings', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_openings', to='companies.department'),
        ),
        migrations.AlterField(
            model_name='jobopening',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('ON_HOLD', 'On Hold'), ('CLOSED', 'Closed')], default='OPEN', max_length=30),
        ),
    ]
