# Generated by Django 6.1 on 2026-08-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0002_remove_employee_branch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='branch',
            name='unique_branch_code_per_company',
        ),
        migrations.RemoveField(
            model_name='department',
            name='branch',
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
